version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}


services:
  postgres:
    build: 
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: postgres_production
    container_name:  postgres_production
    volumes:
      - postgres_data:/var/lib/postgres/data
      - postgres_data_backups:/backups

    env_file:
      - ./.envs/.local/.postgres

  django:
    build: 
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: local_django
    container_name: local_django
    depends_on:
      - postgres

    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres

    ports:
      - "8000:8000"

    command: /start

  
  